/**
 * Devnet simulation: runs REAL transactions against the deployed Mintly program so the demo has
 * verifiable on-chain history (every signature opens on Solana Explorer).
 *
 * For each auction it does: mint a 1/1 NFT -> create_auction -> one bid -> wait for the clock -> winner settles (pay_balance).
 *
 * These are SIMULATED users (wallets generated by this script) — label the numbers as such in the demo.
 * They are not market traction.
 *
 * Usage (from FrontEnd/):
 *   node scripts/devnet_sim.mjs --auctions 3
 * Options / env:
 *   --auctions N          number of auction cycles (default 3 ≈ 25 transactions)
 *   --api URL             also write artworks/sales to the app DB through its API (default http://localhost:3000, "off" to skip)
 *   SOLANA_RPC_URL        use your own RPC (the public devnet RPC rate-limits hard)
 *   FUNDER_KEYPAIR        path to a funded devnet keypair JSON; otherwise the script tries an airdrop
 */
import anchorPkg from "@coral-xyz/anchor";
const { AnchorProvider, BN, Program, Wallet } = anchorPkg;
import { Connection, Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram, Transaction, sendAndConfirmTransaction } from "@solana/web3.js";
import {
  ASSOCIATED_TOKEN_PROGRAM_ID,
  MINT_SIZE,
  TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountIdempotentInstruction,
  createInitializeMintInstruction,
  createMintToInstruction,
  createSyncNativeInstruction,
  getAssociatedTokenAddressSync,
} from "@solana/spl-token";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const arg = (name, def) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
};
const bare = process.argv.slice(2).find((a) => /^\d+$/.test(a));
const AUCTIONS = Number(arg("auctions", bare ?? "3"));
const API = arg("api", "http://localhost:3000");
const RPC = process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
const EXPLORER = (sig) => `https://explorer.solana.com/tx/${sig}?cluster=devnet`;

const conn = new Connection(RPC, "confirmed");
const idl = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../src/idl/mintly_marketplace.json"), "utf-8"));
const PROGRAM_ID = new PublicKey(process.env.NEXT_PUBLIC_MARKETPLACE_PROGRAM_ID || "Cp7nRDpPothhBnSzLv8EmVGQcg4A5HCkmJorw3A3XdRq");
const WSOL = new PublicKey("So11111111111111111111111111111111111111112");
const [configPda] = PublicKey.findProgramAddressSync([Buffer.from("config")], PROGRAM_ID);
const [tokenConfigPda] = PublicKey.findProgramAddressSync([Buffer.from("token"), configPda.toBuffer(), WSOL.toBuffer()], PROGRAM_ID);
const pda = (seed, key) => PublicKey.findProgramAddressSync([Buffer.from(seed), key.toBuffer()], PROGRAM_ID)[0];

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const log = [];
const short = (k) => `${k.toBase58().slice(0, 4)}…${k.toBase58().slice(-4)}`;

async function retry(label, fn, tries = 7) {
  for (let i = 0; ; i++) {
    try {
      return await fn();
    } catch (e) {
      const msg = String(e?.message || e);
      const transient = /429|Too Many|fetch failed|ECONN|ETIMEDOUT|blockhash|timeout|Timed out|socket|503|502/i.test(msg);
      if (!transient || i >= tries) throw e;
      const wait = Math.min(20000, 1200 * 1.7 ** i);
      console.log(`  … ${label}: ${msg.slice(0, 80)} — retry in ${Math.round(wait / 1000)}s`);
      await sleep(wait);
    }
  }
}

function record(kind, signature, extra = {}) {
  log.push({ kind, signature, explorer: EXPLORER(signature), ...extra });
  console.log(`  ✔ ${String(log.length).padStart(2)} ${kind.padEnd(14)} ${signature.slice(0, 20)}…`);
}

const send = (kind, tx, signers) =>
  retry(kind, async () => {
    const sig = await sendAndConfirmTransaction(conn, tx, signers, { commitment: "confirmed" });
    record(kind, sig);
    return sig;
  });

const programFor = (kp) => new Program({ ...idl, address: PROGRAM_ID.toBase58() }, new AnchorProvider(conn, new Wallet(kp), { commitment: "confirmed" }));

// ----------------------------------------------------------------------------- wallets
const walletFile = path.resolve(__dirname, ".sim-wallets.json");
function loadWallets() {
  if (fs.existsSync(walletFile)) {
    const j = JSON.parse(fs.readFileSync(walletFile, "utf-8"));
    return { seller: Keypair.fromSecretKey(Uint8Array.from(j.seller)), bidders: j.bidders.map((b) => Keypair.fromSecretKey(Uint8Array.from(b))) };
  }
  const w = { seller: Keypair.generate(), bidders: [Keypair.generate(), Keypair.generate()] };
  fs.writeFileSync(walletFile, JSON.stringify({ seller: [...w.seller.secretKey], bidders: w.bidders.map((b) => [...b.secretKey]) }));
  return w;
}

async function fund(kp, minSol, funder) {
  const bal = await retry("balance", () => conn.getBalance(kp.publicKey));
  if (bal >= minSol * LAMPORTS_PER_SOL) return;
  const need = Math.ceil((minSol * LAMPORTS_PER_SOL - bal) / 1e6) * 1e6;
  if (funder) {
    const tx = new Transaction().add(SystemProgram.transfer({ fromPubkey: funder.publicKey, toPubkey: kp.publicKey, lamports: need }));
    await send("fund", tx, [funder]);
    return;
  }
  const amount = Math.min(2 * LAMPORTS_PER_SOL, Math.max(need, LAMPORTS_PER_SOL));
  try {
    const sig = await retry("airdrop", () => conn.requestAirdrop(kp.publicKey, amount), 1);
    await retry("airdrop-confirm", async () => {
      const bh = await conn.getLatestBlockhash();
      await conn.confirmTransaction({ signature: sig, ...bh }, "confirmed");
    });
    record("airdrop", sig);
  } catch (e) {
    console.log(`\n✖ The devnet airdrop was refused (${String(e.message).slice(0, 90)}).`);
    console.log(`  Send at least ${minSol.toFixed(2)} devnet SOL to the SELLER address below, then run the script again:`);
    console.log(`    ${kp.publicKey.toBase58()}`);
    console.log("  (free devnet SOL: https://faucet.solana.com — the script shares it with the two bidder wallets),");
    console.log("  or set FUNDER_KEYPAIR=<path to a funded devnet keypair json>.");
    process.exit(1);
  }
}

// ----------------------------------------------------------------------------- steps
async function mintNft(seller) {
  const mint = Keypair.generate();
  const ata = getAssociatedTokenAddressSync(mint.publicKey, seller.publicKey);
  const rent = await retry("rent", () => conn.getMinimumBalanceForRentExemption(MINT_SIZE));
  const tx = new Transaction().add(
    SystemProgram.createAccount({ fromPubkey: seller.publicKey, newAccountPubkey: mint.publicKey, space: MINT_SIZE, lamports: rent, programId: TOKEN_PROGRAM_ID }),
    createInitializeMintInstruction(mint.publicKey, 0, seller.publicKey, seller.publicKey),
    createAssociatedTokenAccountIdempotentInstruction(seller.publicKey, ata, seller.publicKey, mint.publicKey),
    createMintToInstruction(mint.publicKey, ata, seller.publicKey, 1)
  );
  const sig = await send("mint-nft", tx, [seller, mint]);
  return { mint: mint.publicKey, sig };
}

async function createAuction(seller, nftMint, startLamports, durationSec) {
  const program = programFor(seller);
  const auction = pda("auction", nftMint);
  const escrowAuthority = pda("escrow", auction);
  const escrowNft = Keypair.generate();
  const now = Math.floor(Date.now() / 1000);
  const endTime = now + durationSec;
  const revealDeadline = endTime + 86400;
  const depositDeadline = revealDeadline + 86400;
  const paymentDeadline = depositDeadline + 2 * 86400;
  const minIncrement = 5_000_000; // 0.005 SOL — keeps the demo cheap on a faucet budget
  const sig = await retry("create_auction", () =>
    program.methods
      .createAuction(new BN(startLamports), new BN(minIncrement), new BN(now - 30), new BN(endTime), new BN(revealDeadline), new BN(depositDeadline), new BN(paymentDeadline))
      .accounts({
        seller: seller.publicKey,
        config: configPda,
        tokenConfig: tokenConfigPda,
        nftMint,
        paymentMint: WSOL,
        sellerTokenAccount: getAssociatedTokenAddressSync(nftMint, seller.publicKey),
        auction,
        escrowAuthority,
        escrowTokenAccount: escrowNft.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([escrowNft])
      .rpc()
  );
  record("create_auction", sig, { auction: auction.toBase58() });
  return { auction, endTime, minIncrement };
}

async function wrap(kp, lamports) {
  const ata = getAssociatedTokenAddressSync(WSOL, kp.publicKey);
  const tx = new Transaction();
  if (!(await retry("ata-info", () => conn.getAccountInfo(ata)))) {
    tx.add(createAssociatedTokenAccountIdempotentInstruction(kp.publicKey, ata, kp.publicKey, WSOL));
  }
  tx.add(SystemProgram.transfer({ fromPubkey: kp.publicKey, toPubkey: ata, lamports }), createSyncNativeInstruction(ata));
  await send("wrap-sol", tx, [kp]);
  return ata;
}

async function ensureAta(payer, owner) {
  const ata = getAssociatedTokenAddressSync(WSOL, owner, true);
  if (!(await retry("ata-info", () => conn.getAccountInfo(ata)))) {
    await send("create-ata", new Transaction().add(createAssociatedTokenAccountIdempotentInstruction(payer.publicKey, ata, owner, WSOL, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID)), [payer]);
  }
  return ata;
}

async function placeBid(bidder, auction, lamports) {
  const program = programFor(bidder);
  const escrowAuthority = pda("escrow", auction);
  const state = await retry("fetch-auction", () => program.account.auction.fetch(auction));
  const prev = state.highestBidder ?? null;
  const deposit = Math.floor((lamports * 10) / 100);
  const bidderPayment = getAssociatedTokenAddressSync(WSOL, bidder.publicKey);
  const tokenBalance = async () => {
    try {
      return Number((await conn.getTokenAccountBalance(bidderPayment)).value.amount);
    } catch {
      return 0;
    }
  };
  const have = await retry("wsol-balance", tokenBalance);
  if (have < deposit) await wrap(bidder, deposit - have); // also creates the WSOL account the first time

  const escrowAccs = await retry("escrow-accs", () => conn.getParsedTokenAccountsByOwner(escrowAuthority, { mint: WSOL }));
  const escrowKp = escrowAccs.value[0] ? null : Keypair.generate();
  const escrowPayment = escrowAccs.value[0]?.pubkey ?? escrowKp.publicKey;

  let builder = program.methods.placeBid(new BN(lamports)).accounts({
    bidder: bidder.publicKey,
    config: configPda,
    auction,
    bid: PublicKey.findProgramAddressSync([Buffer.from("bid"), auction.toBuffer(), bidder.publicKey.toBuffer()], PROGRAM_ID)[0],
    bidderPaymentAccount: bidderPayment,
    escrowAuthority,
    escrowPaymentAccount: escrowPayment,
    paymentMint: WSOL,
    tokenProgram: TOKEN_PROGRAM_ID,
    systemProgram: SystemProgram.programId,
  });
  if (prev && !prev.equals(bidder.publicKey)) {
    const prevAta = await ensureAta(bidder, prev);
    builder = builder.remainingAccounts([{ pubkey: prevAta, isWritable: true, isSigner: false }]);
  }
  // The IDL flags escrow_payment_account as a signer (it is an init_if_needed account). Once the escrow
  // account exists nobody holds its key, so for every bid after the first it must NOT be a signer.
  const ix = await builder.instruction();
  if (!escrowKp) {
    const meta = ix.keys.find((k) => k.pubkey.equals(escrowPayment));
    if (meta) meta.isSigner = false;
  }
  const signers = [bidder, ...(escrowKp ? [escrowKp] : [])];
  const buildTx = async () => {
    const tx = new Transaction().add(ix);
    tx.feePayer = bidder.publicKey;
    tx.recentBlockhash = (await retry("blockhash", () => conn.getLatestBlockhash())).blockhash;
    tx.sign(...signers);
    return tx;
  };
  // The program deployed on devnet may take a different deposit than the repo source (10%). If the
  // simulation says "insufficient funds", top the WSOL account up to the full bid and try again.
  const sim = await retry("simulate", async () => conn.simulateTransaction(await buildTx()));
  if (sim.value.err && /insufficient funds/i.test(JSON.stringify(sim.value.err) + (sim.value.logs || []).join(" "))) {
    const now = await retry("wsol-balance", tokenBalance);
    if (now < lamports) {
      if (!placeBid.warned) {
        placeBid.warned = true;
        console.log("  ! The deployed program asks for the FULL bid as deposit (repo source says 10%) — topping up the WSOL account.");
      }
      await wrap(bidder, lamports - now);
    }
  } else if (sim.value.err) {
    throw new Error("place_bid would fail: " + JSON.stringify(sim.value.err) + " | " + (sim.value.logs || []).slice(-6).join(" | "));
  }
  const sig = await send("place_bid", new Transaction().add(ix), signers);
  log[log.length - 1].bidder = short(bidder.publicKey);
  log[log.length - 1].sol = lamports / LAMPORTS_PER_SOL;
  return sig;
}

async function payBalance(winner, auction, nftMint, seller) {
  const program = programFor(winner);
  const escrowAuthority = pda("escrow", auction);
  const state = await retry("fetch-auction", () => program.account.auction.fetch(auction));
  const config = await retry("fetch-config", () => program.account.marketplaceConfig.fetch(configPda));
  const remaining = state.currentBid.sub(state.depositPaid).toNumber();
  const winnerPayment = remaining > 0 ? await wrap(winner, remaining) : getAssociatedTokenAddressSync(WSOL, winner.publicKey);
  const winnerNft = getAssociatedTokenAddressSync(nftMint, winner.publicKey);
  await send("create-nft-ata", new Transaction().add(createAssociatedTokenAccountIdempotentInstruction(winner.publicKey, winnerNft, winner.publicKey, nftMint)), [winner]);
  const treasuryAta = await ensureAta(winner, config.treasury);
  const sellerAta = await ensureAta(winner, seller);
  const escrowPayment = (await retry("escrow-pay", () => conn.getParsedTokenAccountsByOwner(escrowAuthority, { mint: WSOL }))).value[0].pubkey;
  const escrowNft = (await retry("escrow-nft", () => conn.getParsedTokenAccountsByOwner(escrowAuthority, { mint: nftMint }))).value[0].pubkey;
  const sig = await retry("pay_balance", () =>
    program.methods
      .payBalance()
      .accounts({
        winner: winner.publicKey,
        config: configPda,
        auction,
        winnerPaymentAccount: winnerPayment,
        escrowAuthority,
        escrowPaymentAccount: escrowPayment,
        escrowNftAccount: escrowNft,
        winnerNftAccount: winnerNft,
        treasuryPaymentAccount: treasuryAta,
        sellerPaymentAccount: sellerAta,
        paymentMint: WSOL,
        nftMint,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc()
  );
  record("pay_balance", sig, { winner: short(winner.publicKey), sol: state.currentBid.toNumber() / LAMPORTS_PER_SOL });
  return { sig, priceSol: state.currentBid.toNumber() / LAMPORTS_PER_SOL };
}

async function postJson(route, body) {
  if (API === "off") return;
  try {
    await fetch(`${API}${route}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  } catch {
    // the app might not be running; the on-chain part is what matters
  }
}

// ----------------------------------------------------------------------------- main
// Settle every auction of the sim seller that already has a bid but is still open (e.g. after an interrupted run).
async function settleAll() {
  const { seller, bidders } = loadWallets();
  const A = bidders[0];
  const program = programFor(A);
  const all = await retry("auctions", () => program.account.auction.all([{ memcmp: { offset: 8, bytes: seller.publicKey.toBase58() } }]));
  const open = all.filter((x) => x.account.currentBid.gt(new BN(0)) && x.account.status.live !== undefined && x.account.highestBidder?.equals(A.publicKey));
  console.log(`${open.length} open auction(s) with a bid to settle`);
  const images = ["/museum3.jpg", "/museum4.jpg", "/museum5.jpg", "/museum6.jpg"];
  let volume = 0;
  for (const [i, x] of open.entries()) {
    const wait = x.account.endTime.toNumber() * 1000 + 5000 - Date.now();
    if (wait > 0) {
      console.log(`  waiting ${Math.ceil(wait / 1000)}s for ${x.publicKey.toBase58().slice(0, 6)}… to end`);
      await sleep(wait);
    }
    console.log(`— Settling ${x.publicKey.toBase58().slice(0, 8)}…`);
    const { priceSol } = await payBalance(A, x.publicKey, x.account.nftMint, seller.publicKey);
    volume += priceSol;
    await postJson("/api/artworks", {
      mintAddress: x.account.nftMint.toBase58(),
      title: `Simulated artwork #${i + 1}`,
      description: "Created by the devnet simulation script (simulated users, not real traction).",
      imageUrl: images[i % images.length],
      creator: seller.publicKey.toBase58(),
      createdAt: Date.now(),
      category: "Simulated · devnet",
      rarity: "collector",
      simulated: true,
    });
    await postJson("/api/sales", {
      mintAddress: x.account.nftMint.toBase58(),
      seller: seller.publicKey.toBase58(),
      buyer: A.publicKey.toBase58(),
      soldAt: Date.now(),
      auctionPda: x.publicKey.toBase58(),
      priceSol,
      simulated: true,
    });
  }
  const outDir = path.resolve(__dirname, "sim-output");
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `devnet-settle-${new Date().toISOString().replace(/[:.]/g, "-")}.json`);
  fs.writeFileSync(outFile, JSON.stringify({ rpc: RPC, program: PROGRAM_ID.toBase58(), transactions: log.length, settledVolumeSol: volume, log }, null, 2));
  console.log(`Done: ${log.length} confirmed transactions, ${open.length} auctions settled, ${volume.toFixed(3)} SOL (simulated users, devnet). Log: ${outFile}`);
}

async function main() {
  if (process.argv.includes("--settle")) return settleAll();
  console.log(`Mintly devnet simulation — ${AUCTIONS} auction cycle(s), RPC ${RPC}`);
  const cfg = await retry("config", () => conn.getAccountInfo(configPda));
  if (!cfg) throw new Error("Marketplace config not found on this cluster. Initialise the marketplace first (scripts/init_marketplace.mjs).");

  const { seller, bidders } = loadWallets();
  const [A, B] = bidders;
  console.log(`seller  ${seller.publicKey.toBase58()}\nbidder1 ${A.publicKey.toBase58()}\nbidder2 ${B.publicKey.toBase58()}`);

  const funder = process.env.FUNDER_KEYPAIR ? Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(process.env.FUNDER_KEYPAIR, "utf-8")))) : null;
  // what each wallet needs: bids + rent + fees (bidder 1 also pays the winning price)
  const needA = 0.05 + 0.05 * AUCTIONS;
  const needB = 0.04 + 0.025 * AUCTIONS;
  const needSeller = 0.04 + 0.03 * AUCTIONS;
  // one funding source is enough: airdrop/transfer to the seller, which then tops up the bidders
  await fund(seller, funder ? needSeller : needSeller + needA + needB + 0.03, funder);
  const bank = funder ?? seller;
  await fund(A, needA, bank);
  await fund(B, needB, bank);

  const images = ["/museum3.jpg", "/museum4.jpg", "/museum5.jpg", "/museum6.jpg"];
  const cycles = [];
  for (let i = 0; i < AUCTIONS; i++) {
    console.log(`\n— Auction ${i + 1}/${AUCTIONS}`);
    const startSol = 0.01 + 0.005 * (i % 3);
    const { mint, sig: mintSig } = await mintNft(seller);
    const { auction, endTime, minIncrement } = await createAuction(seller, mint, Math.round(startSol * LAMPORTS_PER_SOL), 150);
    await placeBid(A, auction, Math.round(startSol * LAMPORTS_PER_SOL));
    // NOTE: one bid per auction. The deployed program creates the escrow token account from a fresh keypair on the
    // first bid and then requires that keypair to sign every later bid (ConstraintSigner), so a second bid cannot
    // be sent. See the report for the fix (use an associated token account for the escrow).
    cycles.push({ i, mint, auction, endTime, mintSig, image: images[i % images.length] });
  }

  const lastEnd = Math.max(...cycles.map((c) => c.endTime));
  const waitMs = Math.max(0, (lastEnd + 5) * 1000 - Date.now());
  if (waitMs > 0) {
    console.log(`\nWaiting ${Math.ceil(waitMs / 1000)}s for the last auction to end…`);
    await sleep(waitMs);
  }

  let volume = 0;
  for (const c of cycles) {
    console.log(`\n— Settling auction ${c.i + 1}`);
    const { priceSol } = await payBalance(A, c.auction, c.mint, seller.publicKey);
    volume += priceSol;
    await postJson("/api/artworks", {
      mintAddress: c.mint.toBase58(),
      title: `Simulated artwork #${c.i + 1}`,
      description: "Created by the devnet simulation script (simulated users, not real traction).",
      imageUrl: c.image,
      creator: seller.publicKey.toBase58(),
      createdAt: Date.now(),
      signature: c.mintSig,
      category: "Simulated · devnet",
      rarity: "collector",
      simulated: true,
    });
    await postJson("/api/sales", {
      mintAddress: c.mint.toBase58(),
      seller: seller.publicKey.toBase58(),
      buyer: A.publicKey.toBase58(),
      soldAt: Date.now(),
      auctionPda: c.auction.toBase58(),
      priceSol,
      simulated: true,
    });
  }

  const outDir = path.resolve(__dirname, "sim-output");
  fs.mkdirSync(outDir, { recursive: true });
  const outFile = path.join(outDir, `devnet-sim-${new Date().toISOString().replace(/[:.]/g, "-")}.json`);
  fs.writeFileSync(outFile, JSON.stringify({ rpc: RPC, program: PROGRAM_ID.toBase58(), transactions: log.length, settledVolumeSol: volume, log }, null, 2));
  console.log(`\nDone: ${log.length} confirmed transactions, ${AUCTIONS} auctions settled, ${volume.toFixed(2)} SOL settled volume (simulated users, devnet).`);
  console.log(`Signatures + Explorer links: ${outFile}`);
}

main().catch((e) => {
  console.log("\n✖ Simulation stopped:", e?.message || e);
  if (log.length) console.log(`  ${log.length} transaction(s) were confirmed before the error.`);
  process.exit(1);
});
