"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "vi";

export type TranslationKey =
  | "nav.explore" | "nav.create" | "nav.auctions" | "nav.portfolio" | "nav.fieldStudio" | "nav.connect" | "nav.disconnect"
  | "nav.search" | "nav.collections" | "nav.menu" | "nav.language"
  | "footer.provenance" | "footer.manifesto" | "footer.support" | "footer.privacy" | "footer.terms"
  | "footer.tagline" | "footer.backToTop"
  | "home.activeAuctions" | "home.directListings" | "home.highestBid" | "home.liveSolana"
  | "home.heroTitle" | "home.heroTitleAccent" | "home.heroDescription" | "home.exploreAuctions" | "home.createArtwork"
  | "home.decentralized" | "home.verifiedEscrow" | "home.instantSettlement" | "home.floorPrice" | "home.marketVolume" | "home.activeSellers"
  | "home.featuredAuction" | "home.currentBid" | "home.liveOnChain" | "home.loadingAuction" | "home.noAuctions"
  | "home.inventoryEyebrow" | "home.inventoryTitle" | "home.viewAll" | "home.syncing" | "home.noListings" | "home.firstToMint"
  | "home.onChainProvenance" | "home.onChainProvenanceText" | "home.builtForCreators" | "home.builtForCreatorsText" | "home.everyDevice" | "home.everyDeviceText"
  | "home.smartContractVerified" | "home.readyToMint" | "home.mintYourWork"
  | "auctions.eyebrow" | "auctions.title" | "auctions.description" | "auctions.liveOnSolana" | "auctions.auctionCount" | "auctions.highestBid" | "auctions.noBids" | "auctions.contractState" | "auctions.verifiedActive" | "auctions.loading" | "auctions.emptyTitle" | "auctions.emptyText" | "auctions.liveBidding" | "auctions.ended" | "auctions.escrow" | "auctions.seller" | "auctions.currentBid"
  | "detail.loading" | "detail.notFound" | "detail.notFoundText" | "detail.backAuctions" | "detail.live" | "detail.concluded" | "detail.provenance" | "detail.auctionPda" | "detail.nftMint" | "detail.lotCollection" | "detail.createdBy" | "detail.leadingBid" | "detail.startingPrice" | "detail.highestBidder" | "detail.enterBid" | "detail.placeBid" | "detail.placing" | "detail.bidConfirmed" | "detail.escrowText" | "detail.settlement" | "detail.bidHistory" | "detail.noBidsText" | "detail.firstBidder"
  | "settlement.exit" | "settlement.won" | "settlement.description" | "settlement.loading" | "settlement.noLot" | "settlement.lot" | "settlement.pending" | "settlement.depositDue" | "settlement.secures" | "settlement.remaining" | "settlement.connectedWallet" | "settlement.gas" | "settlement.submitting" | "settlement.secure" | "settlement.confirmed" | "settlement.rules" | "settlement.walletDisconnected"
  | "wallet.connecting" | "wallet.copied" | "wallet.copy" | "wallet.disconnect" | "card.directSale" | "card.buyNow" | "card.bid" | "card.by"
  | "passport.title" | "passport.subtitle" | "passport.identity" | "passport.mint" | "passport.creator" | "passport.owner" | "passport.supply" | "passport.creation" | "passport.artworkHash" | "passport.metadataHash" | "passport.proof" | "passport.provenance" | "passport.activity" | "passport.notAvailable" | "passport.verify" | "passport.back"
  | "verify.title" | "verify.subtitle" | "verify.placeholder" | "verify.button" | "verify.invalid" | "verify.found" | "verify.notFound" | "verify.evidence" | "verify.owner" | "verify.supply" | "verify.metadataPending" | "verify.proofPending"
  | "ai.title" | "ai.checking" | "ai.unavailable" | "ai.pending" | "ai.evidence" | "ai.scanNow" | "ai.original" | "ai.duplicateWarning" | "ai.originality"
  | "create.connectTitle" | "create.connectText" | "create.connectPhantom" | "create.provenance" | "create.artworkTitle" | "create.titlePlaceholder" | "create.statement" | "create.statementPlaceholder" | "create.editions" | "create.unique" | "create.network" | "create.properties" | "create.medium" | "create.style" | "create.platform" | "create.digital" | "create.freehand" | "create.connectMint" | "create.preview" | "create.mintArtifact" | "create.readyToDraw" | "create.zoom"
  | "tool.pencil" | "tool.eraser" | "tool.text" | "tool.fill" | "tool.eyedropper" | "tool.pixel" | "tool.upload" | "tool.size" | "tool.customColor" | "tool.zoomOut" | "tool.zoomIn" | "tool.fullscreen" | "tool.undo" | "tool.redo" | "tool.clear"
  | "mint.title" | "mint.description" | "mint.estFee" | "mint.cancel" | "mint.confirm" | "mint.preparing" | "mint.preparingText" | "mint.awaitingWallet" | "mint.awaitingWalletText" | "mint.confirming" | "mint.confirmingText" | "mint.success" | "mint.address" | "mint.viewExplorer" | "mint.viewPortfolio" | "mint.backCanvas" | "mint.failed" | "mint.close" | "mint.tryAgain" | "mint.artworkPreview" | "mint.network"
  | "create.uploadImage" | "create.dropImage"
  | "portfolio.title" | "portfolio.subtitle" | "portfolio.totalCreated" | "portfolio.verifiedOnChain" | "portfolio.all" | "portfolio.emptyTitle" | "portfolio.emptyText" | "portfolio.createNow" | "portfolio.viewPassport" | "portfolio.listSale" | "portfolio.download" | "portfolio.createdOn"
  | "common.loading";

const translations: Record<Locale, Record<TranslationKey, string>> = {
  en: {
    "nav.explore": "Explore", "nav.create": "Create", "nav.auctions": "Auctions", "nav.portfolio": "My Vault", "nav.fieldStudio": "Field / Studio", "nav.connect": "Connect Phantom", "nav.disconnect": "Disconnect wallet", "nav.search": "Search", "nav.collections": "Collections", "nav.menu": "Toggle menu", "nav.language": "Language",
    "footer.provenance": "Provenance", "footer.manifesto": "Manifesto", "footer.support": "Support", "footer.privacy": "Privacy", "footer.terms": "Terms", "footer.tagline": "The art of provenance.", "footer.backToTop": "Back to top",
    "home.activeAuctions": "Active Auctions", "home.directListings": "Direct Listings", "home.highestBid": "Highest Bid", "home.liveSolana": "Live on Solana", "home.heroTitle": "Own the", "home.heroTitleAccent": "energy of the match.", "home.heroDescription": "Discover on-chain football moments, creator editions, and live decentralized bidding powered by Solana smart contracts.", "home.exploreAuctions": "Explore Auctions", "home.createArtwork": "Create Artwork", "home.decentralized": "Decentralized", "home.verifiedEscrow": "Verified Escrow", "home.instantSettlement": "Instant Settlement", "home.floorPrice": "Floor Price", "home.marketVolume": "Market Volume", "home.activeSellers": "Active Sellers", "home.featuredAuction": "Featured Auction", "home.currentBid": "Current Bid", "home.liveOnChain": "Live On-Chain", "home.loadingAuction": "Loading on-chain auction...", "home.noAuctions": "No active auctions. Mint and start an auction!", "home.inventoryEyebrow": "Decentralized Inventory", "home.inventoryTitle": "On-Chain Listings & Drops", "home.viewAll": "View all auctions", "home.syncing": "Syncing with Solana Program...", "home.noListings": "No active listings found.", "home.firstToMint": "Be the first to mint and list your artwork on-chain!", "home.onChainProvenance": "On-chain provenance", "home.onChainProvenanceText": "Each collectible is tied to a verifiable, unique auction record and signature trail on Solana.", "home.builtForCreators": "Built for creators", "home.builtForCreatorsText": "From rough sketch to final collectible, mint and list in seconds with escrow security.", "home.everyDevice": "Made for every device", "home.everyDeviceText": "Optimized for mobile, tablet, laptop, and desktop so anyone can discover, bid, and create.", "home.smartContractVerified": "Smart Contract Verified", "home.readyToMint": "Ready to mint and trade on Solana", "home.mintYourWork": "Mint your work",
    "auctions.eyebrow": "Smart Contract Escrow", "auctions.title": "Decentralized Auctions", "auctions.description": "Bid on one-of-a-kind digital artifacts with automatic non-custodial escrow on Solana.", "auctions.liveOnSolana": "Live on Solana", "auctions.auctionCount": "auction", "auctions.highestBid": "Highest Bid", "auctions.noBids": "No bids yet", "auctions.contractState": "Contract State", "auctions.verifiedActive": "Verified Active", "auctions.loading": "Loading on-chain auctions...", "auctions.emptyTitle": "No active auctions.", "auctions.emptyText": "Create and launch the first on-chain auction with your NFT!", "auctions.liveBidding": "Live Bidding", "auctions.ended": "Ended", "auctions.escrow": "Solana Escrow", "auctions.seller": "Seller", "auctions.currentBid": "Current Bid",
    "detail.loading": "Loading on-chain auction details...", "detail.notFound": "Auction Not Found", "detail.notFoundText": "The requested account is not an active auction on-chain.", "detail.backAuctions": "Back to all auctions", "detail.live": "LIVE AUCTION", "detail.concluded": "AUCTION CONCLUDED", "detail.provenance": "Smart Contract Provenance", "detail.auctionPda": "Auction PDA", "detail.nftMint": "NFT Mint", "detail.lotCollection": "Lot Collection", "detail.createdBy": "Created & listed by", "detail.leadingBid": "Current Leading Bid", "detail.startingPrice": "Starting Price", "detail.highestBidder": "Highest Bidder", "detail.enterBid": "Enter Bid in SOL", "detail.placeBid": "Place Bid", "detail.placing": "Placing...", "detail.bidConfirmed": "Bid confirmed on Solana! Tx:", "detail.escrowText": "Funds held in non-custodial smart contract escrow.", "detail.settlement": "Settlement Flow", "detail.bidHistory": "On-Chain Bids", "detail.noBidsText": "No bids recorded on-chain yet.", "detail.firstBidder": "Be the first bidder!",
    "settlement.exit": "Exit to Auctions", "settlement.won": "YOU WON.", "settlement.description": "Secure your on-chain acquisition. Complete the 10% smart contract deposit to finalize provenance.", "settlement.loading": "Loading lot...", "settlement.noLot": "No active lot", "settlement.lot": "ON-CHAIN AUCTION LOT", "settlement.pending": "Pending", "settlement.depositDue": "10% DEPOSIT DUE NOW", "settlement.secures": "Secures asset in program escrow", "settlement.remaining": "Remaining 90%", "settlement.connectedWallet": "CONNECTED WALLET", "settlement.gas": "Gas", "settlement.submitting": "Submitting to Solana...", "settlement.secure": "Secure My NFT (Pay Deposit)", "settlement.confirmed": "10% Deposit Confirmed on Solana!", "settlement.rules": "Smart contract rules require deposit completion within the designated deadline to prevent forfeiture.", "settlement.walletDisconnected": "Wallet Disconnected",
    "wallet.connecting": "Connecting...", "wallet.copied": "Copied!", "wallet.copy": "Copy Address", "wallet.disconnect": "Disconnect", "card.directSale": "Direct Sale", "card.buyNow": "Buy now", "card.bid": "Bid", "card.by": "By",
    "passport.title": "NFT Passport", "passport.subtitle": "A verifiable lifecycle record for this digital asset.", "passport.identity": "Identity", "passport.mint": "Mint Address", "passport.creator": "Creator", "passport.owner": "Current Owner", "passport.supply": "Supply", "passport.creation": "Creation Proof", "passport.artworkHash": "Artwork Hash", "passport.metadataHash": "Metadata Hash", "passport.proof": "Proof status", "passport.provenance": "Provenance", "passport.activity": "Activity", "passport.notAvailable": "Not available on-chain yet", "passport.verify": "Verify on Solana", "passport.back": "Back to marketplace",
    "verify.title": "Verify NFT", "verify.subtitle": "Inspect on-chain evidence for a Solana mint address.", "verify.placeholder": "Paste mint address", "verify.button": "Verify NFT", "verify.invalid": "Enter a valid Solana mint address.", "verify.found": "Mint account found on Solana", "verify.notFound": "Mint account was not found on this network.", "verify.evidence": "Evidence", "verify.owner": "Largest token holder", "verify.supply": "Supply", "verify.metadataPending": "Metadata and creator proof require a readable metadata account.", "verify.proofPending": "Creation proof is not embedded on-chain yet.",
    "ai.title": "AI Similarity / Duplicate Detection", "ai.checking": "Analyzing artwork...", "ai.unavailable": "AI provider is not configured.", "ai.pending": "Similarity analysis ready.", "ai.evidence": "Evidence fingerprint", "ai.scanNow": "Scan AI Similarity", "ai.original": "Original Artwork (Verified)", "ai.duplicateWarning": "Warning: High Duplicate Risk", "ai.originality": "Originality",
    "create.connectTitle": "Connect your wallet to start creating", "create.connectText": "Your wallet is your creator identity on MINTLY.", "create.connectPhantom": "Connect Phantom", "create.provenance": "Provenance", "create.artworkTitle": "Artwork Title", "create.titlePlaceholder": "Untitled Opus", "create.statement": "Curatorial Statement", "create.statementPlaceholder": "Describe the conceptual foundation...", "create.editions": "Editions", "create.unique": "1/1 Unique", "create.network": "Network", "create.properties": "Properties", "create.medium": "Medium", "create.style": "Style", "create.platform": "Platform", "create.digital": "Digital", "create.freehand": "Freehand", "create.connectMint": "Connect your wallet to mint this artifact", "create.preview": "Preview", "create.mintArtifact": "Mint Artifact", "create.readyToDraw": "Ready to draw", "create.zoom": "Zoom", "create.uploadImage": "Upload Image File", "create.dropImage": "Drop image here to load onto canvas",
    "tool.pencil": "Pencil", "tool.eraser": "Eraser", "tool.text": "Text", "tool.fill": "Fill", "tool.eyedropper": "Eyedropper", "tool.pixel": "Pixel mode", "tool.upload": "Upload Image", "tool.size": "Size", "tool.customColor": "Custom color", "tool.zoomOut": "Zoom out", "tool.zoomIn": "Zoom in", "tool.fullscreen": "Toggle fullscreen", "tool.undo": "Undo", "tool.redo": "Redo", "tool.clear": "Clear canvas",
    "mint.title": "Mint Artifact", "mint.description": "Description", "mint.estFee": "Est. Fee", "mint.cancel": "Cancel", "mint.confirm": "Confirm Mint", "mint.preparing": "Preparing Metadata...", "mint.preparingText": "Uploading art and metadata to decentralized storage.", "mint.awaitingWallet": "Awaiting Wallet Signature...", "mint.awaitingWalletText": "Phantom is requesting your signature.", "mint.confirming": "Confirming on Solana...", "mint.confirmingText": "Submitting the transaction to the Solana network.", "mint.success": "Successfully Minted!", "mint.address": "Address", "mint.viewExplorer": "View on Solana Explorer", "mint.viewPortfolio": "View in My Vault", "mint.backCanvas": "Back to Canvas", "mint.failed": "Minting Failed", "mint.close": "Close", "mint.tryAgain": "Try Again", "mint.artworkPreview": "Artwork preview", "mint.network": "Network",
    "portfolio.title": "Creator Vault & Collection", "portfolio.subtitle": "Verifiable 1-of-1 digital artworks created and owned by your Solana wallet.", "portfolio.totalCreated": "Artworks Minted", "portfolio.verifiedOnChain": "Verified On-Chain", "portfolio.all": "All Artifacts", "portfolio.emptyTitle": "No artworks created yet", "portfolio.emptyText": "Your wallet has not minted any digital artifacts yet. Jump into the Studio to craft your first 1/1 NFT!", "portfolio.createNow": "Create New Artwork", "portfolio.viewPassport": "Artwork Passport", "portfolio.listSale": "List for Sale", "portfolio.download": "Download HD", "portfolio.createdOn": "Minted on",
    "common.loading": "Loading...",
  },
  vi: {
    "nav.explore": "Khám phá", "nav.create": "Sáng tạo", "nav.auctions": "Đấu giá", "nav.portfolio": "Kho tác phẩm", "nav.fieldStudio": "Không gian / Studio", "nav.connect": "Kết nối Phantom", "nav.disconnect": "Ngắt kết nối ví", "nav.search": "Tìm kiếm", "nav.collections": "Bộ sưu tập", "nav.menu": "Mở menu", "nav.language": "Ngôn ngữ",
    "footer.provenance": "Nguồn gốc", "footer.manifesto": "Tuyên ngôn", "footer.support": "Hỗ trợ", "footer.privacy": "Riêng tư", "footer.terms": "Điều khoản", "footer.tagline": "Nghệ thuật của nguồn gốc.", "footer.backToTop": "Về đầu trang",
    "home.activeAuctions": "Đấu giá đang diễn ra", "home.directListings": "Tác phẩm đang bán", "home.highestBid": "Giá cao nhất", "home.liveSolana": "Đang hoạt động trên Solana", "home.heroTitle": "Sở hữu", "home.heroTitleAccent": "năng lượng của trận đấu.", "home.heroDescription": "Khám phá những khoảnh khắc bóng đá on-chain, các phiên bản của nghệ sĩ và đấu giá phi tập trung trên smart contract Solana.", "home.exploreAuctions": "Khám phá đấu giá", "home.createArtwork": "Tạo tác phẩm", "home.decentralized": "Phi tập trung", "home.verifiedEscrow": "Escrow đã xác thực", "home.instantSettlement": "Thanh toán tức thì", "home.floorPrice": "Giá sàn", "home.marketVolume": "Khối lượng giao dịch", "home.activeSellers": "Người bán hoạt động", "home.featuredAuction": "Phiên đấu giá nổi bật", "home.currentBid": "Giá hiện tại", "home.liveOnChain": "Đang diễn ra on-chain", "home.loadingAuction": "Đang tải phiên đấu giá...", "home.noAuctions": "Chưa có phiên đấu giá. Hãy mint và bắt đầu ngay!", "home.inventoryEyebrow": "Kho tác phẩm phi tập trung", "home.inventoryTitle": "Tác phẩm on-chain & bộ sưu tập mới", "home.viewAll": "Xem tất cả đấu giá", "home.syncing": "Đang đồng bộ với Solana...", "home.noListings": "Chưa tìm thấy tác phẩm đang bán.", "home.firstToMint": "Hãy là người đầu tiên mint và đăng bán tác phẩm on-chain!", "home.onChainProvenance": "Nguồn gốc on-chain", "home.onChainProvenanceText": "Mỗi tác phẩm gắn với hồ sơ đấu giá độc nhất và chuỗi chữ ký có thể xác minh trên Solana.", "home.builtForCreators": "Dành cho người sáng tạo", "home.builtForCreatorsText": "Từ bản phác thảo đến tác phẩm hoàn chỉnh, mint và đăng bán trong vài giây với escrow bảo mật.", "home.everyDevice": "Mọi thiết bị đều phù hợp", "home.everyDeviceText": "Tối ưu cho điện thoại, máy tính bảng và máy tính để ai cũng có thể khám phá, đấu giá và sáng tạo.", "home.smartContractVerified": "Smart contract đã xác minh", "home.readyToMint": "Sẵn sàng mint và giao dịch trên Solana", "home.mintYourWork": "Mint tác phẩm",
    "auctions.eyebrow": "Escrow smart contract", "auctions.title": "Đấu giá phi tập trung", "auctions.description": "Đấu giá các tác phẩm kỹ thuật số độc bản với escrow tự động, không lưu ký trên Solana.", "auctions.liveOnSolana": "Đang hoạt động trên Solana", "auctions.auctionCount": "phiên", "auctions.highestBid": "Giá cao nhất", "auctions.noBids": "Chưa có lượt trả giá", "auctions.contractState": "Trạng thái contract", "auctions.verifiedActive": "Đã xác minh", "auctions.loading": "Đang tải các phiên đấu giá...", "auctions.emptyTitle": "Chưa có phiên đấu giá.", "auctions.emptyText": "Hãy tạo và khởi chạy phiên đấu giá on-chain đầu tiên với NFT của bạn!", "auctions.liveBidding": "Đang trả giá", "auctions.ended": "Đã kết thúc", "auctions.escrow": "Escrow Solana", "auctions.seller": "Người bán", "auctions.currentBid": "Giá hiện tại",
    "detail.loading": "Đang tải chi tiết phiên đấu giá...", "detail.notFound": "Không tìm thấy phiên đấu giá", "detail.notFoundText": "Tài khoản được yêu cầu không phải phiên đấu giá on-chain đang hoạt động.", "detail.backAuctions": "Quay lại tất cả đấu giá", "detail.live": "ĐANG ĐẤU GIÁ", "detail.concluded": "ĐÃ KẾT THÚC", "detail.provenance": "Nguồn gốc smart contract", "detail.auctionPda": "PDA đấu giá", "detail.nftMint": "NFT Mint", "detail.lotCollection": "Bộ sưu tập", "detail.createdBy": "Được tạo và đăng bởi", "detail.leadingBid": "Giá đang dẫn đầu", "detail.startingPrice": "Giá khởi điểm", "detail.highestBidder": "Người trả giá cao nhất", "detail.enterBid": "Nhập giá trả bằng SOL", "detail.placeBid": "Đặt giá", "detail.placing": "Đang đặt...", "detail.bidConfirmed": "Đã xác nhận giá trên Solana! Tx:", "detail.escrowText": "Tiền được giữ trong escrow smart contract không lưu ký.", "detail.settlement": "Quy trình thanh toán", "detail.bidHistory": "Lượt trả giá on-chain", "detail.noBidsText": "Chưa có lượt trả giá nào trên chain.", "detail.firstBidder": "Hãy là người đầu tiên trả giá!",
    "settlement.exit": "Rời trang đấu giá", "settlement.won": "BẠN ĐÃ THẮNG.", "settlement.description": "Hoàn tất quyền sở hữu on-chain. Thanh toán 10% tiền đặt cọc để xác nhận nguồn gốc.", "settlement.loading": "Đang tải lô đấu giá...", "settlement.noLot": "Không có lô đang hoạt động", "settlement.lot": "LÔ ĐẤU GIÁ ON-CHAIN", "settlement.pending": "Đang chờ", "settlement.depositDue": "ĐẶT CỌC 10% NGAY BÂY GIỜ", "settlement.secures": "Bảo đảm tài sản trong escrow của chương trình", "settlement.remaining": "Còn lại 90%", "settlement.connectedWallet": "VÍ ĐÃ KẾT NỐI", "settlement.gas": "Gas", "settlement.submitting": "Đang gửi lên Solana...", "settlement.secure": "Nhận NFT (Thanh toán đặt cọc)", "settlement.confirmed": "Đã xác nhận đặt cọc 10% trên Solana!", "settlement.rules": "Quy tắc smart contract yêu cầu hoàn tất đặt cọc đúng hạn để tránh bị mất khoản đặt cọc.", "settlement.walletDisconnected": "Ví chưa kết nối",
    "wallet.connecting": "Đang kết nối...", "wallet.copied": "Đã sao chép!", "wallet.copy": "Sao chép địa chỉ", "wallet.disconnect": "Ngắt kết nối", "card.directSale": "Bán trực tiếp", "card.buyNow": "Mua ngay", "card.bid": "Đặt giá", "card.by": "Bởi",
    "passport.title": "Hộ chiếu NFT", "passport.subtitle": "Hồ sơ vòng đời có thể xác minh của tài sản số này.", "passport.identity": "Định danh", "passport.mint": "Địa chỉ mint", "passport.creator": "Người tạo", "passport.owner": "Chủ sở hữu hiện tại", "passport.supply": "Nguồn cung", "passport.creation": "Proof sáng tạo", "passport.artworkHash": "Hash tác phẩm", "passport.metadataHash": "Hash metadata", "passport.proof": "Trạng thái proof", "passport.provenance": "Nguồn gốc", "passport.activity": "Hoạt động", "passport.notAvailable": "Chưa có dữ liệu on-chain", "passport.verify": "Xác minh trên Solana", "passport.back": "Quay lại marketplace",
    "verify.title": "Xác minh NFT", "verify.subtitle": "Kiểm tra bằng chứng on-chain cho địa chỉ mint Solana.", "verify.placeholder": "Dán địa chỉ mint", "verify.button": "Xác minh NFT", "verify.invalid": "Hãy nhập địa chỉ mint Solana hợp lệ.", "verify.found": "Đã tìm thấy tài khoản mint trên Solana", "verify.notFound": "Không tìm thấy tài khoản mint trên mạng này.", "verify.evidence": "Bằng chứng", "verify.owner": "Chủ token lớn nhất", "verify.supply": "Nguồn cung", "verify.metadataPending": "Cần metadata account có thể đọc để xác minh metadata và creator.", "verify.proofPending": "Proof sáng tạo chưa được ghi trực tiếp lên chain.",
    "ai.title": "AI kiểm tra tương đồng / trùng lặp", "ai.checking": "Đang phân tích tác phẩm...", "ai.unavailable": "Chưa cấu hình AI provider.", "ai.pending": "Sẵn sàng kiểm tra tương đồng.", "ai.evidence": "Fingerprint bằng chứng", "ai.scanNow": "Quét AI tương đồng", "ai.original": "Tác phẩm độc bản (Đã xác minh)", "ai.duplicateWarning": "Cảnh báo: Trùng lặp cao", "ai.originality": "Độ nguyên bản",
    "create.connectTitle": "Kết nối ví để bắt đầu sáng tạo", "create.connectText": "Ví là danh tính của bạn với tư cách nghệ sĩ trên MINTLY.", "create.connectPhantom": "Kết nối Phantom", "create.provenance": "Nguồn gốc", "create.artworkTitle": "Tên tác phẩm", "create.titlePlaceholder": "Tác phẩm chưa đặt tên", "create.statement": "Tuyên ngôn tác phẩm", "create.statementPlaceholder": "Mô tả ý tưởng và nền tảng của tác phẩm...", "create.editions": "Phiên bản", "create.unique": "Độc bản 1/1", "create.network": "Mạng lưới", "create.properties": "Thuộc tính", "create.medium": "Chất liệu", "create.style": "Phong cách", "create.platform": "Nền tảng", "create.digital": "Kỹ thuật số", "create.freehand": "Vẽ tự do", "create.connectMint": "Kết nối ví để mint tác phẩm này", "create.preview": "Xem trước", "create.mintArtifact": "Mint tác phẩm", "create.readyToDraw": "Sẵn sàng vẽ", "create.zoom": "Thu phóng", "create.uploadImage": "Tải file ảnh lên", "create.dropImage": "Thả file ảnh vào đây để mở lên khung vẽ",
    "tool.pencil": "Bút chì", "tool.eraser": "Tẩy", "tool.text": "Chữ", "tool.fill": "Tô màu", "tool.eyedropper": "Hút màu", "tool.pixel": "Chế độ pixel", "tool.upload": "Tải ảnh lên", "tool.size": "Kích thước", "tool.customColor": "Màu tùy chỉnh", "tool.zoomOut": "Thu nhỏ", "tool.zoomIn": "Phóng to", "tool.fullscreen": "Toàn màn hình", "tool.undo": "Hoàn tác", "tool.redo": "Làm lại", "tool.clear": "Xóa khung vẽ",
    "mint.title": "Mint tác phẩm", "mint.description": "Mô tả", "mint.estFee": "Phí ước tính", "mint.cancel": "Hủy", "mint.confirm": "Xác nhận mint", "mint.preparing": "Đang chuẩn bị metadata...", "mint.preparingText": "Đang tải tác phẩm và metadata lên bộ nhớ phi tập trung.", "mint.awaitingWallet": "Đang chờ chữ ký ví...", "mint.awaitingWalletText": "Phantom đang yêu cầu bạn ký giao dịch.", "mint.confirming": "Đang xác nhận trên Solana...", "mint.confirmingText": "Đang gửi giao dịch lên mạng Solana.", "mint.success": "Mint thành công!", "mint.address": "Địa chỉ", "mint.viewExplorer": "Xem trên Solana Explorer", "mint.viewPortfolio": "Xem trong Kho Tác Phẩm", "mint.backCanvas": "Quay lại khung vẽ", "mint.failed": "Mint thất bại", "mint.close": "Đóng", "mint.tryAgain": "Thử lại", "mint.artworkPreview": "Xem trước tác phẩm", "mint.network": "Mạng lưới",
    "portfolio.title": "Kho tác phẩm & Bộ sưu tập của bạn", "portfolio.subtitle": "Các tác phẩm độc bản 1/1 được tạo và lưu trữ trên chuỗi Solana thuộc sở hữu của ví bạn.", "portfolio.totalCreated": "Tác phẩm đã Mint", "portfolio.verifiedOnChain": "Đã xác thực on-chain", "portfolio.all": "Tất cả tác phẩm", "portfolio.emptyTitle": "Chưa có tác phẩm nào", "portfolio.emptyText": "Ví của bạn chưa tạo tác phẩm nào. Hãy vào Studio để vẽ và mint ngay NFT độc bản đầu tiên!", "portfolio.createNow": "Tạo tác phẩm mới ngay", "portfolio.viewPassport": "Hộ chiếu NFT", "portfolio.listSale": "Đăng bán", "portfolio.download": "Tải ảnh gốc HD", "portfolio.createdOn": "Tạo lúc",
    "common.loading": "Đang tải...",
  },
};

interface I18nContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  toggleLocale: () => void;
  t: (key: TranslationKey) => string;
}

const I18nContext = createContext<I18nContextValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("vi");

  useEffect(() => {
    try {
      const saved = window.localStorage.getItem("mintly-locale");
      if (saved === "en" || saved === "vi") {
        setLocaleState(saved);
      }
    } catch {
      // Ignore storage errors
    }
  }, []);

  useEffect(() => {
    try {
      window.localStorage.setItem("mintly-locale", locale);
      document.documentElement.lang = locale;
    } catch {
      // Ignore storage errors
    }
  }, [locale]);

  const value = useMemo<I18nContextValue>(() => ({
    locale,
    setLocale: (nextLocale) => setLocaleState(nextLocale),
    toggleLocale: () => setLocaleState((current) => current === "en" ? "vi" : "en"),
    t: (key) => translations[locale]?.[key] || translations.en[key] || key,
  }), [locale]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);
  if (!context) throw new Error("useI18n must be used inside I18nProvider");
  return context;
}
